#include "modules\core\player\systems\items\items_models.pwn"
#include "modules\core\player\systems\items\items_utils.pwn"
#include "modules\core\player\systems\items\items_core.pwn"
#include "modules\core\player\systems\items\items_drop.pwn"
#include "modules\core\player\systems\items\items_give.pwn"
#include "modules\core\player\systems\items\items_config.pwn"
#include "modules\core\player\systems\items\items_cmd.pwn"
#include "modules\core\player\systems\items\items_callbacks.pwn"