#include <YSI_Coding\y_hooks>

#include "modules\core\maps\maps_main.pwn"

#include "modules\core\maps\exterior\streets.pwn"
#include "modules\core\maps\exterior\cityhall.pwn"
#include "modules\core\maps\exterior\tolls.pwn"
#include "modules\core\maps\exterior\twintowers.pwn"
//#include "modules\core\maps\exterior\ferriswheel.pwn"

#include "modules\core\maps\exterior\factions\LSFD.pwn"
#include "modules\core\maps\exterior\factions\newton.pwn"
#include "modules\core\maps\exterior\factions\SAN1.pwn" 
#include "modules\core\maps\exterior\factions\SEB.pwn" 

#include "modules\core\maps\exterior\workshops\montgomery.pwn" 

#include "modules\core\maps\exterior\env\idlewood.pwn"
#include "modules\core\maps\exterior\env\sanpedro.pwn"
#include "modules\core\maps\exterior\env\bahamas.pwn"
#include "modules\core\maps\exterior\env\SM.pwn"
#include "modules\core\maps\exterior\env\westmont.pwn"
#include "modules\core\maps\exterior\env\creenshaw.pwn"
#include "modules\core\maps\exterior\env\jefferson_park.pwn"
#include "modules\core\maps\exterior\env\jefferson_motel.pwn"
#include "modules\core\maps\exterior\env\ls_freeway.pwn"
#include "modules\core\maps\exterior\env\eastls_church.pwn"
#include "modules\core\maps\exterior\env\eastls_carwash.pwn"
//#include "modules\core\maps\exterior\env\willowfield.pwn"
#include "modules\core\maps\exterior\env\el_corona.pwn"
#include "modules\core\maps\exterior\env\ocean_willow.pwn"
#include "modules\core\maps\exterior\env\sp_apartments.pwn"
#include "modules\core\maps\exterior\env\vinewood_sign.pwn"
#include "modules\core\maps\exterior\env\skatepark.pwn"
#include "modules\core\maps\exterior\env\jefferson_hs.pwn"
#include "modules\core\maps\exterior\env\ganton.pwn"

#include "modules\core\maps\exterior\business\petshop.pwn"
//#include "modules\core\maps\exterior\business\stacked.pwn"

#include "modules\core\maps\interior\factions\SAN2.pwn"
#include "modules\core\maps\interior\factions\LSPD_interior.pwn"
#include "modules\core\maps\interior\mazebank.pwn"
#include "modules\core\maps\interior\doj.pwn"
#include "modules\core\maps\interior\nightclub1.pwn"
#include "modules\core\maps\interior\hospital.pwn"

// HOUSES
#include "modules\core\maps\interior\houses\house1.pwn"
#include "modules\core\maps\interior\houses\house2.pwn"
#include "modules\core\maps\interior\houses\house3.pwn"
#include "modules\core\maps\interior\houses\house4.pwn"
#include "modules\core\maps\interior\houses\house5.pwn"
#include "modules\core\maps\interior\houses\house6.pwn"
#include "modules\core\maps\interior\houses\house7.pwn"
#include "modules\core\maps\interior\houses\house8.pwn"
#include "modules\core\maps\interior\houses\house9.pwn"
#include "modules\core\maps\interior\houses\house10.pwn"
#include "modules\core\maps\interior\houses\house11.pwn"
#include "modules\core\maps\interior\houses\house12.pwn"

// GARAGES
#include "modules\core\maps\interior\garages\garage1.pwn"
#include "modules\core\maps\interior\garages\garage2.pwn"
#include "modules\core\maps\interior\garages\garage3.pwn"
#include "modules\core\maps\interior\garages\garage4.pwn"